### PR TITLE
Custom attribute handling

### PR DESCRIPTION
**Pull request by bdharrington7**
Didn't know if you would mind a PR, but this change addresses #1

### CODE REVIEW

**Comment by akhoury** [comment]
did you test this with and without the `rel` attribute?

**Comment by bdharrington7** [comment]
Yes, it still passes all of the unit tests, and I tested manually with and without the `rel` attribute

**Comment by bdharrington7** [comment]
Note this is very Vanilla Quotes -> NodeBB syntax specific. NodeBB specific in the fact that it prepends an `@` symbol and appends `said:`

This PR would just make it easier for me to deploy / utilize the nodebb-plugin-import plugin

**Comment by akhoury** [comment]
ok published
`html-md-optional_window@3.0.3`
and
`nodebb-plugin-import@0.3.10` which now uses the latest html-md-optional_window

**Comment by akhoury** [comment]
im taking your word for it :P

**Comment by bdharrington7** [comment]
thanks!

**Pull request merged**
